# overlay_advice.py
"""
Overlay YOLO boxes and advice text onto a video, taking:
 - the original video (--video)
 - the JSONL file (--json) generated by moto_advice_pipeline.py

For each annotated frame (frame_id), we:
 - draw the YOLO detection boxes on that frame
 - display the advice text for the next 25 frames, automatically wrapping long text
 - use white text instead of yellow

Usage:
    python overlay_advice.py --video test.mp4 \
        --json results/results.jsonl \
        --output advised_video.mp4
"""

import cv2
import json
import argparse
from pathlib import Path
from typing import List, Dict, Any

# Number of frames to display each advice
ADVICE_DURATION = 25

# YOLO box colors per class (BGR). Default white if not listed.
CLASS_COLORS = {
    "car":         (0, 255, 0),    # green
    "motorcycle":  (0, 0, 255),    # red
    "truck":       (255, 0, 0),    # blue
    "person":      (255, 255, 0),  # cyan
}

# Text color for advice (white). To use red, replace with (0, 0, 255).
ADVICE_COLOR = (255, 255, 255)


def load_annotations(jsonl_path: Path) -> List[Dict[str, Any]]:
    """
    Reads the JSONL file and returns a list of dicts.
    Each dict has: frame_id, timestamp, image_path, caption, advice, objects.
    """
    records = []
    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            records.append(json.loads(line.strip()))
    return records


def draw_boxes(frame, objects: List[Dict[str, Any]]):
    """
    Draw YOLO bounding boxes onto the frame.
    Each object dict must have:
      - 'class_name' (str)
      - 'bbox': [x1, y1, x2, y2]
    """
    for obj in objects:
        cls_name = obj.get("class_name", "unknown")
        x1, y1, x2, y2 = map(int, obj["bbox"])
        color = CLASS_COLORS.get(cls_name, (255, 255, 255))  # white if not in CLASS_COLORS
        cv2.rectangle(frame, (x1, y1), (x2, y2), color, thickness=2)

        # Draw label background
        label = f"{cls_name}"
        (w, h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
        cv2.rectangle(frame, (x1, y1 - h - 4), (x1 + w, y1), color, thickness=-1)
        cv2.putText(frame, label, (x1, y1 - 2),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)


def wrap_text(text: str, max_width: int, font, font_scale: float, thickness: int) -> List[str]:
    """
    Splits 'text' into multiple lines so that each line's pixel width ≤ max_width.
    Returns a list of lines. Uses cv2.getTextSize to measure pixel width.
    """
    words = text.split()
    lines = []
    current = ""
    for w in words:
        test_line = current + (" " if current else "") + w
        (w_px, _), _ = cv2.getTextSize(test_line, font, font_scale, thickness)
        if w_px <= max_width:
            current = test_line
        else:
            if current:
                lines.append(current)
            current = w
    if current:
        lines.append(current)
    return lines


def main():
    parser = argparse.ArgumentParser(
        description="Overlay YOLO boxes and advice text onto a video"
    )
    parser.add_argument("--video",   type=str, required=True, help="Path to input video")
    parser.add_argument("--json",    type=str, required=True, help="Path to JSONL annotations")
    parser.add_argument("--output",  type=str, required=True, help="Path for output video")
    args = parser.parse_args()

    video_path = Path(args.video)
    jsonl_path = Path(args.json)
    output_path = Path(args.output)

    # 1) Load all annotations into a list
    records = load_annotations(jsonl_path)

    # 2) Build a map: frame_id → {"objects": ..., "advice": ...}
    annotations_map = {}
    for rec in records:
        fid = rec["frame_id"]
        annotations_map[fid] = {
            "objects": rec["objects"],
            "advice": rec["advice"]
        }

    # 3) Open source video
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open video {video_path}")

    fps          = cap.get(cv2.CAP_PROP_FPS)
    width        = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height       = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    # 4) Create VideoWriter for the output
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(output_path), fourcc, fps, (width, height))

    # 5) Track active advice (list of {"text": ..., "end_frame": ...})
    active_advice = []

    frame_id = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # 5.1) If this frame was annotated, add its advice to active_advice
        if frame_id in annotations_map:
            ann = annotations_map[frame_id]
            advice_text = ann["advice"]
            # Display from this frame up to (frame_id + ADVICE_DURATION - 1)
            active_advice.append({
                "text": advice_text,
                "end_frame": frame_id + ADVICE_DURATION - 1
            })
            # Draw boxes immediately for this sampled frame
            draw_boxes(frame, ann["objects"])

        # 5.2) Render all active advice on this frame
        new_active = []
        y_offset = 40  # starting vertical offset for the first advice line

        for advice in active_advice:
            if frame_id <= advice["end_frame"]:
                # Wrap long advice into multiple lines
                lines = wrap_text(
                    advice["text"],
                    max_width=width - 20,         # leave 10px margin each side
                    font=cv2.FONT_HERSHEY_SIMPLEX,
                    font_scale=0.6,
                    thickness=2
                )
                # Draw each line in white (or change ADVICE_COLOR to (0,0,255) for red)
                for line in lines:
                    cv2.putText(frame, line, (10, y_offset),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, ADVICE_COLOR, 2, cv2.LINE_AA)
                    y_offset += 25
                y_offset += 10  # extra spacing between separate advice blocks
                new_active.append(advice)

        active_advice = new_active

        # 5.3) Write this annotated frame to output
        writer.write(frame)
        frame_id += 1

    # 6) Release resources
    cap.release()
    writer.release()
    print(f"Output video written to: {output_path} (total frames: {total_frames})")


if __name__ == "__main__":
    main()
